# Generated by Django 4.1.6 on 2023-03-31 03:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('nombre_departamento', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('serial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('codigo_qr', models.URLField()),
                ('tipo', models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Impresora', 'Impresora'), ('Monitor', 'Monitor'), ('Otro', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actas.departamento')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut_funcionario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(help_text='Ingrese un email válido con dominio @municoquimbo.cl', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actas.cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('rut_tecnico', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_problema', models.CharField(max_length=50)),
                ('estado_equipo', models.CharField(choices=[('En espera', 'En espera'), ('En reparacion', 'En reparacion'), ('Reparado', 'Reparado'), ('No reparado', 'No reparado')], default='En espera', max_length=50)),
                ('perifericos', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('No Aplica', 'No Aplica'), ('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Cable de poder', 'Cable de poder'), ('Cargador', 'Cargador'), ('Cable de USB', 'Cable de USB'), ('Pantalla', 'Pantalla')], max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('descripcion_reparacion', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actas.equipo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actas.funcionario')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actas.tecnico')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingreso',
            },
        ),
    ]
