# Generated by Django 4.1.6 on 2023-03-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnico',
            options={'verbose_name': 'Tecnico', 'verbose_name_plural': 'Tecnicos'},
        ),
        migrations.AlterModelTable(
            name='tecnico',
            table='Tecnico',
        ),
    ]
