# Generated by Django 4.1.6 on 2023-03-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actas', '0002_alter_tecnico_options_alter_tecnico_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_qr',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
