# Generated by Django 4.1.6 on 2023-03-31 15:18

import Actas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actas', '0003_remove_funcionario_cargo_alter_equipo_codigo_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_qr'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rut_funcionario',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[Actas.models.validate_rut]),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='rut_tecnico',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[Actas.models.validate_rut]),
        ),
    ]
