# Generated by Django 4.1.6 on 2023-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actas', '0004_alter_equipo_codigo_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='rut_funcionario',
            field=models.CharField(help_text='el rut debe ser con puntos y guión', max_length=12, primary_key=True, serialize=False),
        ),
    ]
