# Generated by Django 4.1.6 on 2023-04-03 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actas', '0005_alter_funcionario_rut_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
