# Generated by Django 4.1.6 on 2023-04-06 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actas', '0006_tecnico_apellido_tecnico_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='media/codigos_qr'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
