# Generated by Django 4.1.6 on 2023-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actas', '0007_alter_equipo_codigo_qr_alter_tecnico_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
